name: Update and release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set manifest.json version
        uses: jossef/action-set-json-field@v2
        with:
          file: custom_components/havvarsel/manifest.json
          field: version
          value: ${{ github.ref_name }}

      - name: Commit the updated manifest and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add custom_components/havvarsel/manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "Update manifest version to ${{ github.ref_name }}"
            git push origin HEAD:main
          fi

          # Move the tag to this commit and force-push
          git tag -f ${{ github.ref_name }}
          git push origin ${{ github.ref_name }} --force

  release:
    needs: update-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "(zipped artifact)" > ${{ github.workspace }}/custom_components/havvarsel/README.md
        
      # Pack the havvarsel dir as a zip and upload to the release
      - name: 📦 ZIP HAVVARSEL Dir
        run: |
          cd ${{ github.workspace }}/custom_components/havvarsel
          zip havvarsel.zip -r ./

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/havvarsel/havvarsel.zip
