name: Update and release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update version in manifest.json
        run: |
          cd ${{ github.workspace }}/custom_components/havvarsel
          jq '.version = "${{ steps.get_version.outputs.VERSION }}"' manifest.json > manifest.json.tmp
          mv manifest.json.tmp manifest.json

      - name: Commit the updated manifest and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add custom_components/havvarsel/manifest.json
          if ! git diff --cached --quiet; then
            git commit -m "Update manifest version to ${{ github.ref_name }}"
            git push origin HEAD:main
          fi

          # Move the tag to this commit and force-push
          git tag -f ${{ github.ref_name }}
          git push origin ${{ github.ref_name }} --force

  release:
    needs: update-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # Force checkout of main branch to get the updated manifest
        
      # Pack the havvarsel dir as a zip and upload to the release
      - name: 📦 ZIP HAVVARSEL Dir
        run: |
          cd ${{ github.workspace }}/custom_components/havvarsel
          zip havvarsel.zip -r ./

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/havvarsel/havvarsel.zip
