name: Zip me up

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          name: havvarsel download
          files: apps/ 
          dest: havvarsel.zip
      - uses: actions/upload-artifact@v1.1
        with:
          name: havvarsel download
          path: ${{ github.workspace }}/havvarsel.zip
